import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.AdmissibleClass
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.BridgeLemmas
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.GateLemmas
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.FinalTheorem
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.InvariantFunctionalStructure
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.PalaisPrinciple
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.InfiniteDimensionalMorseTheory
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.MinimaxPrinciple
import VariationalAspectsGroupActionsInfiniteCanonicalLaneLean.EndpointClassification

namespace HautevilleHouse
namespace VariationalAspectsGroupActionsInfiniteCanonicalLaneLean

theorem variational_endgame_complete (A : AdmissibleClass) :
    ConstrainedVariationalGroupActionClosure A := by
  exact constrained_variational_group_action_endgame A

end VariationalAspectsGroupActionsInfiniteCanonicalLaneLean
end HautevilleHouse